[2022-01-27 16:28:29,177] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: cgi_40.load_to_hdfs 2022-01-27T16:28:16.884428+00:00 [queued]>
[2022-01-27 16:28:29,185] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: cgi_40.load_to_hdfs 2022-01-27T16:28:16.884428+00:00 [queued]>
[2022-01-27 16:28:29,185] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-01-27 16:28:29,185] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-01-27 16:28:29,185] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-01-27 16:28:29,193] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): load_to_hdfs> on 2022-01-27T16:28:16.884428+00:00
[2022-01-27 16:28:29,200] {standard_task_runner.py:52} INFO - Started process 124 to run task
[2022-01-27 16:28:29,202] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cgi_40', 'load_to_hdfs', '2022-01-27T16:28:16.884428+00:00', '--job-id', '23', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/cgi40_dag.py', '--cfg-path', '/tmp/tmpgzqxax_f', '--error-file', '/tmp/tmp2g1fnvuo']
[2022-01-27 16:28:29,202] {standard_task_runner.py:77} INFO - Job 23: Subtask load_to_hdfs
[2022-01-27 16:28:29,229] {logging_mixin.py:104} INFO - Running <TaskInstance: cgi_40.load_to_hdfs 2022-01-27T16:28:16.884428+00:00 [running]> on host ca77e06d0f72
[2022-01-27 16:28:29,257] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=oulespaul@gmail.com
AIRFLOW_CTX_DAG_OWNER=ETDA
AIRFLOW_CTX_DAG_ID=cgi_40
AIRFLOW_CTX_TASK_ID=load_to_hdfs
AIRFLOW_CTX_EXECUTION_DATE=2022-01-27T16:28:16.884428+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-27T16:28:16.884428+00:00
[2022-01-27 16:28:29,416] {logging_mixin.py:104} INFO - 'Stored!'
[2022-01-27 16:28:29,422] {logging_mixin.py:104} INFO - {'FileStatuses': {'FileStatus': [{'accessTime': 1643300313514,
                                  'blockSize': 134217728,
                                  'childrenNum': 0,
                                  'fileId': 90588,
                                  'group': 'cloudera',
                                  'length': 0,
                                  'modificationTime': 1643300313519,
                                  'owner': 'cloudera',
                                  'pathSuffix': 'CGI_4.0_2017_2019_20220127161833.csv',
                                  'permission': '755',
                                  'replication': 1,
                                  'storagePolicy': 0,
                                  'type': 'FILE'},
                                 {'accessTime': 1643300909326,
                                  'blockSize': 134217728,
                                  'childrenNum': 0,
                                  'fileId': 90589,
                                  'group': 'cloudera',
                                  'length': 14797638,
                                  'modificationTime': 1643300909414,
                                  'owner': 'cloudera',
                                  'pathSuffix': 'CGI_4.0_2017_2019_20220127162829.csv',
                                  'permission': '755',
                                  'replication': 1,
                                  'storagePolicy': 0,
                                  'type': 'FILE'}]}}
[2022-01-27 16:28:29,423] {python.py:151} INFO - Done. Returned value was: None
[2022-01-27 16:28:29,430] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=cgi_40, task_id=load_to_hdfs, execution_date=20220127T162816, start_date=20220127T162829, end_date=20220127T162829
[2022-01-27 16:28:29,455] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-27 16:28:29,494] {local_task_job.py:151} INFO - Task exited with return code 0
